from __future__ import annotations

from .frpc_config import FrpcConfig
from .services import Service

_HEADER = "# Generated by aws-reverse-tunnel. Do not edit by hand."


def parse_target(target: str) -> tuple[str, int]:
    """Parse and validate a "host:port" target, shared by the CLI and renderer."""
    host, sep, port_str = target.rpartition(":")
    if not sep or not host or not port_str.isdigit():
        raise ValueError(f"invalid target {target!r}; expected host:port")
    return host, int(port_str)


def render(config: FrpcConfig, services: dict[str, Service]) -> str:
    lines = [
        _HEADER,
        f'serverAddr = "{config.server_addr}"',
        f"serverPort = {config.server_port}",
        'auth.method = "token"',
        f'auth.token = "{config.token}"',
    ]
    for name, service in sorted(services.items()):
        host, port = parse_target(service.target)
        lines += [
            "",
            "[[proxies]]",
            f'name = "{name}"',
            f'type = "{service.proto}"',
            f'localIP = "{host}"',
            f"localPort = {port}",
        ]
        if service.proto == "http":
            lines.append(f'customDomains = ["{name}.{config.base_domain}"]')
        else:
            lines.append(f"remotePort = {service.remote_port}")
    return "\n".join(lines) + "\n"
